"""Add project.date column

Revision ID: 37bef1f2d26e
Revises: d7a26d3f4258
Create Date: 2025-07-11 04:25:08.412212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bef1f2d26e'
down_revision = 'd7a26d3f4258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
