"""section images

Revision ID: b41bee49f5bc
Revises: c43a16a7a347
Create Date: 2025-07-30 11:06:20.069766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41bee49f5bc'
down_revision = 'c43a16a7a347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_section', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
