"""Add subtitle and other fields to Project

Revision ID: d7a26d3f4258
Revises: 
Create Date: 2025-07-11 04:07:19.473223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a26d3f4258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('client', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('collaboration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('completion_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('service',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('market',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('date')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('date', sa.TEXT(), nullable=True))
        batch_op.alter_column('market',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('service',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('collaboration')
        batch_op.drop_column('client')
        batch_op.drop_column('location')
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
