"""delete project image

Revision ID: dc72bc8e95fd
Revises: b41bee49f5bc
Create Date: 2025-07-30 11:32:36.168589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc72bc8e95fd'
down_revision = 'b41bee49f5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_cover', sa.BOOLEAN(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=True),
    sa.Column('layout_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('caption', sa.VARCHAR(length=255), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
